module.exports = {
  notFoundArticle: "Такой статьи не существует",
  forbiddenDelete: "Невозможно удалить чужую статью",
  validationError: "Ошибка валидации",
  userDoesntExists: "Такого пользователя не существует",
  emailExists: "Пользователь с такой почтой уже есть",
  needAuth: "Необходима авторизация",
  serverError: "На сервере произошла ошибка",
  wrongPassOrEmail: "Неправильные почта или пароль",
  invalidLink: "Некорректная ссылка",
  pageNotFound: "Страница не найдена",
  enterEmail: "Email - обязательное поле, введите корректный email-адрес",
  incorrectName: "Введите Имя от 2 до 30 символов",
  enterPass: "Пароль - обязательное поле от 8 до 30 символов",
  notHex: "Id недопустимого формата",
  enterKeyword: "Keyword - обязательноe поле",
  enterTitle: "Title - обязательноe поле",
  enterText: "Text - обязательноe поле",
  enterDate: "Date - обязательноe поле",
  enterSource: "Source - обязательноe поле",
};
